name = "krladiesworld-api"
main = "src/index.ts"
compatibility_date = "2024-04-01"

[[d1_databases]]
binding = "DB"
database_name = "krladiesworld-db"
database_id = "41261a5a-2131-4939-a621-9565521ff5e5"
